server:
  port: 8080

spring:
  application:
    name: apigateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: microservice-product
          uri: lb://microservice-product
          predicates:
            - Path=/api/products/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1s
                  factor: 2
        - id: microservice-product-swagger
          uri: lb://microservice-product
          predicates:
            - Path=/microservice-product/swagger-ui/**, /microservice-product/v3/api-docs, /microservice-product/v3/api-docs/**
          filters:
            - RewritePath=/microservice-product/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/microservice-product/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}
            - RewritePath=/microservice-product/v3/api-docs, /v3/api-docs


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
